### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by jwiegley** [gallais/parseque#2]
Hi @gallais,

I'm trying to build a very simple parser that reads 3 field lines into the following data structure:

``` coq
Record Coords := {
  coordTime      : N;
  coordLatitude  : Q;
  coordLongitude : Q
}.
```

I've tried starting with this grammar:

``` coq
Record Language (n : nat) : Type := MkLanguage
  { _expr   : Parser Toks ascii M (NEList Coords) n
  }.

Arguments MkLanguage {_}.

Definition language (n : nat) : Language n :=
  MkLanguage (nelist (((Build_Coords <$> decimal_N) <*> decimal_N) <*> decimal_N)).
```

However, it's giving me errors that I don't quite understand. Is there a trick to passing parsers to multi-argument constructors?  I don't grok yet what Box'ing is, and why/when it's needed.  Thanks!

**Comment by gallais** [comment]
> I don't grok yet what Box'ing is, and why/when it's needed

If you don't mind the Agda-based presentation, I have [this draft](https://gallais.github.io/pdf/agdarsec17.pdf) (which I'll have finalised by Sunday) explaining the library's design.

The gist of it is: `Box` marks positions where it is safe to make a recursive call to the grammar being defined because some of the input has been consumed already. However they shouldn't be a hindrance in Coq because implicit coercions should happily coerce a `Parser` to a `Box`ed `Parser`.

As for the error. I can't reproduce it. This is what I have (I got rid of `N` and `Q` because I don't have parsers for these):

```coq
Require Import Parseque.
Require Import NEList.
Require Import Sized.
Require Import Ascii.

Section Coords.

Context
  {Toks : nat -> Type} `{Sized Toks ascii}
  {M : Type -> Type} `{RawMonad M} `{RawAlternative M}.

Record Coords := {
  coordTime      : nat;
  coordLatitude  : nat;
  coordLongitude : nat
}.

Record Language (n : nat) : Type := MkLanguage
  { _expr   : Parser Toks ascii M (NEList Coords) n
  }.

Arguments MkLanguage {_}.

Definition language (n : nat) : Language n :=
  MkLanguage (nelist (((Build_Coords <$> decimal_nat) <*> decimal_nat) <*> decimal_nat)).
```

**Comment by jwiegley** [comment]
Ah! It was because I hadn't written float_Q yet, of course. Thank you!

**Comment by jwiegley** [comment]
Also, you may want to associate `<*>` and `<$>` similarly to Haskell....

**Comment by gallais** [comment]
My brain hurts every time I have to pick levels for my notations in Coq because the order is reversed with respect to Agda AFAICR. I should really get around to dealing with this TODO: https://github.com/gallais/parseque/blob/master/src/Combinators.v#L237

**Comment by jwiegley** [comment]
I use these in [coq-haskell](https://github.com/jwiegley/coq-haskell) for what it's worth:

``` coq
Infix "<$>" := fmap (at level 28, left associativity, only parsing).
Infix "<*>" := ap (at level 28, left associativity).
```
